swagger: '2.0'
info:
  version: '1.0'
  title: "WastelessAPI"
schemes:
  - https
paths:
  "/add-point":
    options:
      description: "Handling CORS for the add-point API"
      responses:
        200:
      x-amazon-apigateway-integration:
        responses:
          statusCode: "200",
          responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Correlation-ID'",
              method.response.header.Access-Control-Allow-Methods : "'POST'",
              method.response.header.Access-Control-Allow-Origin": "'*'"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"     
    post:
      description: "Add a new point to the wasteless map"
      consumes:
        - application/json
      responses:
        200:
          description: "The point was added successfully"
      x-amazon-apigateway-integration:
        uri: ${add_point_lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"

